lib/what_where_when_web/router.ex
defmodule WhatWhereWhenWeb.Router do
  use WhatWhereWhenWeb, :router

  import WhatWhereWhenWeb.PersonAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {WhatWhereWhenWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_person
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_current_person
  end

  scope "/", WhatWhereWhenWeb do
    pipe_through [:browser, :redirect_if_person_is_authenticated]
  end

  scope "/", WhatWhereWhenWeb do
    pipe_through [:browser, :require_authenticated_person]

    resources "/events", EventController, only: [:new, :create]
  end

  scope "/", WhatWhereWhenWeb do
    pipe_through :browser

    get "/", PageController, :index

    post "/who/me", PersonSessionController, :new
    get "/api/auth", PersonSessionController, :create

    resources "/who/me", PersonController, only: [:show], singleton: true do
      pipe_through [:require_authenticated_person]
      resources "/events", EventController, only: [:edit, :update, :show]
    end

    delete "/who/me", PersonSessionController, :delete

    resources "/who/camps", CampController, only: [:show] do
      pipe_through [:require_authenticated_person]
      resources "/events", EventController, only: [:edit, :update]
    end

    get "/what", EventCategoryController, :index
    get "/where", LocationController, :index
    get "/when", EventController, :index

    resources "/events", EventController, only: [:show]
  end

  scope "/api", WhatWhereWhenWeb do
    pipe_through :api

    get "/event/categories", EventCategoryController, :index
    get "/events", EventController, :index
  end

  if Mix.env() === :dev do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      post "/api/auth", WhatWhereWhenWeb.PersonSessionController, :create
      live_dashboard "/dashboard", metrics: WhatWhereWhenWeb.Telemetry
    end
  end
end

# get "/people/confirm", PersonConfirmationController, :new
# post "/people/confirm", PersonConfirmationController, :create
# get "/people/confirm/:token", PersonConfirmationController, :edit
# post "/people/confirm/:token", PersonConfirmationController, :update

# scope "/", WhatWhereWhenWeb do
#   pipe_through [:browser, :redirect_if_person_is_authenticated]

#   get "/people/register", PersonRegistrationController, :new
#   post "/people/register", PersonRegistrationController, :create

#   get "/people/reset_password", PersonResetPasswordController, :new
#   post "/people/reset_password", PersonResetPasswordController, :create
#   get "/people/reset_password/:token", PersonResetPasswordController, :edit
#   put "/people/reset_password/:token", PersonResetPasswordController, :update
# end

# scope "/", WhatWhereWhenWeb do
#   pipe_through [:browser, :require_authenticated_person]

#   get "/people/settings", PersonSettingsController, :edit
#   put "/people/settings", PersonSettingsController, :update
#   get "/people/settings/confirm_email/:token", PersonSettingsController, :confirm_email
# end

lib/what_where_when/locations.ex
defmodule WhatWhereWhen.Locations do
  @moduledoc """
  The Locations context.
  """

  import Ecto.Query, warn: false
  alias WhatWhereWhen.Repo

  alias WhatWhereWhen.Locations.Location

  @doc """
  Returns the list of locations.

  ## Examples

      iex> list_locations()
      [%Location{}, ...]

  """
  def list_locations do
    Repo.all(Location)
  end

  @doc """
  Gets a single location.

  Raises `Ecto.NoResultsError` if the Location does not exist.

  ## Examples

      iex> get_location!(123)
      %Location{}

      iex> get_location!(456)
      ** (Ecto.NoResultsError)

  """
  def get_location!(id), do: Repo.get!(Location, id)

  @doc """
  Creates a location.

  ## Examples

      iex> create_location(%{field: value})
      {:ok, %Location{}}

      iex> create_location(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_location(attrs \\ %{}) do
    %Location{}
    |> Location.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a location.

  ## Examples

      iex> update_location(location, %{field: new_value})
      {:ok, %Location{}}

      iex> update_location(location, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_location(%Location{} = location, attrs) do
    location
    |> Location.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a location.

  ## Examples

      iex> delete_location(location)
      {:ok, %Location{}}

      iex> delete_location(location)
      {:error, %Ecto.Changeset{}}

  """
  def delete_location(%Location{} = location) do
    Repo.delete(location)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking location changes.

  ## Examples

      iex> change_location(location)
      %Ecto.Changeset{data: %Location{}}

  """
  def change_location(%Location{} = location, attrs \\ %{}) do
    Location.changeset(location, attrs)
  end
end

lib/what_where_when/locations/location.ex
defmodule WhatWhereWhen.Locations.Location do
  use Ecto.Schema
  import Ecto.Changeset

  schema "locations" do
    field :type, Ecto.Enum, values: [camp: 1, event: 2, infra: 3]

    field :lat, :decimal
    field :lng, :decimal
    field :description, :string
  end

  @doc false
  def changeset(location, attrs) do
    cs =
      location
      |> cast(attrs, [:type, :lat, :lng, :description])
      |> validate_required([:type])

    case get_field(cs, :description) do
      x when x == "" or is_nil(x) ->
        cs |> validate_required([:lat, :lng])

      _ ->
        cs
    end
  end
end

lib/what_where_when_web/controllers/location_controller.ex
defmodule WhatWhereWhenWeb.LocationController do
  use WhatWhereWhenWeb, :controller

  alias WhatWhereWhen.Locations

  def index(conn, _params) do
    locations = Locations.list_locations()
    render(conn, "index.html", locations: locations)
  end
end

lib/what_where_when_web/views/location_view.ex
defmodule WhatWhereWhenWeb.LocationView do
  use WhatWhereWhenWeb, :view
end

lib/what_where_when_web/templates/location/edit.html.heex
<h1>Edit Location</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.location_path(@conn, :update, @location)) %>

<span><%= link "Back", to: Routes.location_path(@conn, :index) %></span>

lib/what_where_when_web/templates/location/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :latitude %>
  <%= number_input f, :latitude, step: "any" %>
  <%= error_tag f, :latitude %>

  <%= label f, :longitude %>
  <%= number_input f, :longitude, step: "any" %>
  <%= error_tag f, :longitude %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/what_where_when_web/templates/location/index.html.heex
<h1 class="italic">Oh the places you'll go...</h1>

<div id="map" class="flex-grow basis-full flex"></div>
<script phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/map.js")}></script>

<script type="text/javascript">
  (function(){mountMap(document.getElementById("map"))})();
</script>

lib/what_where_when_web/templates/location/new.html.heex
<h1>New Location</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.location_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.location_path(@conn, :index) %></span>

lib/what_where_when_web/templates/location/show.html.heex
<h1>Show Location</h1>

<ul>

  <li>
    <strong>Latitude:</strong>
    <%= @location.latitude %>
  </li>

  <li>
    <strong>Longitude:</strong>
    <%= @location.longitude %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.location_path(@conn, :edit, @location) %></span> |
<span><%= link "Back", to: Routes.location_path(@conn, :index) %></span>