lib/what_where_when_web/router.ex
defmodule WhatWhereWhenWeb.Router do
  use WhatWhereWhenWeb, :router

  import WhatWhereWhenWeb.PersonAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {WhatWhereWhenWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_person
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_current_person
  end

  scope "/", WhatWhereWhenWeb do
    pipe_through [:browser, :redirect_if_person_is_authenticated]
  end

  scope "/", WhatWhereWhenWeb do
    pipe_through [:browser, :require_authenticated_person]

    resources "/events", EventController, only: [:new, :create]
  end

  scope "/", WhatWhereWhenWeb do
    pipe_through :browser

    get "/", PageController, :index

    post "/who/me", PersonSessionController, :new
    get "/api/auth", PersonSessionController, :create

    resources "/who/me", PersonController, only: [:show], singleton: true do
      pipe_through [:require_authenticated_person]
      resources "/events", EventController, only: [:edit, :update, :show]
    end

    delete "/who/me", PersonSessionController, :delete

    resources "/who/camps", CampController, only: [:show] do
      pipe_through [:require_authenticated_person]
      resources "/events", EventController, only: [:edit, :update]
    end

    get "/what", EventCategoryController, :index
    get "/where", LocationController, :index
    get "/when", EventController, :index

    resources "/events", EventController, only: [:show]
  end

  scope "/api", WhatWhereWhenWeb do
    pipe_through :api

    get "/event/categories", EventCategoryController, :index
    get "/events", EventController, :index
  end

  if Mix.env() === :dev do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      post "/api/auth", WhatWhereWhenWeb.PersonSessionController, :create
      live_dashboard "/dashboard", metrics: WhatWhereWhenWeb.Telemetry
    end
  end
end

# get "/people/confirm", PersonConfirmationController, :new
# post "/people/confirm", PersonConfirmationController, :create
# get "/people/confirm/:token", PersonConfirmationController, :edit
# post "/people/confirm/:token", PersonConfirmationController, :update

# scope "/", WhatWhereWhenWeb do
#   pipe_through [:browser, :redirect_if_person_is_authenticated]

#   get "/people/register", PersonRegistrationController, :new
#   post "/people/register", PersonRegistrationController, :create

#   get "/people/reset_password", PersonResetPasswordController, :new
#   post "/people/reset_password", PersonResetPasswordController, :create
#   get "/people/reset_password/:token", PersonResetPasswordController, :edit
#   put "/people/reset_password/:token", PersonResetPasswordController, :update
# end

# scope "/", WhatWhereWhenWeb do
#   pipe_through [:browser, :require_authenticated_person]

#   get "/people/settings", PersonSettingsController, :edit
#   put "/people/settings", PersonSettingsController, :update
#   get "/people/settings/confirm_email/:token", PersonSettingsController, :confirm_email
# end

lib/what_where_when_web/views/layout_view.ex
defmodule WhatWhereWhenWeb.LayoutView do
  use WhatWhereWhenWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/what_where_when_web/templates/layout/_footer.html.heex
<footer
  class="px-4 py-2  min-h-10 w-full bg-slate-600 flex flex-wrap flex-row justify-around text-amber-200 underline flex-shrink-0"
>

  <a href="https://volunteer.fireflyartscollective.org/">Volunteer</a>
  <a href="https://www.fireflyartscollective.org/getting-ready/survival-guide/">Guide</a>
  <a href="https://airtable.com/shrrDNEUC657KRPCK">Report an Incident</a>
</footer>

lib/what_where_when_web/templates/layout/_header.html.heex
<%= if @current_person do %>
<header class="flex flex-row justify-items-stretch justify-between flex-initial">
  <section
    id="header-logo"
    class="w-[79px] mr-1 md:basis-full md:flex-2 md:flex-grow"
  >
  <%# max-w-[238px]" <-- is logo + "Firefly" %>

    <a href="/">
      <img width="400" height="83" class="object-left object-cover
      min-h-[83px]" src={Routes.static_path(@conn, "/images/firefly-logo.png")}
      alt="What Where When"/>
    </a>

  </section>
  <section id="person-menu" class="py-4 md:flex-shrink">
    <ul class="flex-1 flex flex-col justify-center h-full">
      <li>
        <%= link @current_person.burn_name || @current_person.email, to: Routes.person_path(@conn, :show) %>
      </li>
      <%= if @current_person.camp do %>
     <li>
        [<%= link @current_person.camp.name, to: Routes.camp_path(@conn,
        :show, @current_person.camp.id) %>]
      </li>
      <% end %>
    </ul>
  </section>
</header>

<% else %>
<header class="flex flex-row justify-between pt-5 flex-shrink-0">
  <section id="header-logo" class="md:w-1/2 basis-initial w-9/12">
    <a href="/">
      <img class="w-auto" src={Routes.static_path(@conn,
      "/images/firefly-logo.png")} alt="What Where When"/>
    </a>
  </section>
  <section id="person-menu" class="py-4">
    <%= link "Log in", to: Routes.person_session_path(@conn, :new), method: :post, class:
    "ring-2 p-3 bg-blue-400" %>
  </section>
</header>
<% end %>

lib/what_where_when_web/templates/layout/_nav.html.heex
<nav
  class="flex flex-row justify-around h-10 bg-amber-100 border-b-2 border-yellow-200 text-cyan-700 children:ring-1 children:p-2 children:mt-0.5 children:bg-yellow-100 flex-shrink-0"
>

  <%= link "When", to: Routes.event_path(@conn, :index) %>

  <%= if @current_person  do%>
    <%= link "+", to: Routes.event_path(@conn, :new), class: "bg-green-200 font-semibold" %>
  <% end %>
</nav>

lib/what_where_when_web/templates/layout/app.html.heex
<main class="mx-2.5 pt-1 min-w-[60%] max-w-5xl sm:mx-auto flex-grow basis-full flex flex-col">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/what_where_when_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/what_where_when_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en" class="bg-black">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="height=device-height, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <meta name="theme-color" content="#2563eb">
    <meta name="start-date" content={Firefly.start_date}>
    <meta name="end-date" content={Firefly.end_date}>

    <%= live_title_tag assigns[:page_title] || "", suffix: " · Firefly WhatWhereWhen" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/map.css")}/>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/calendar.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="bg-slate-500 font-sans text-white flex flex-col max-w-7xl xl:mx-auto">
    <%= render "_header.html", assigns %>
    <%= render "_nav.html", assigns %>
    <%= @inner_content %>
    <%= render "_footer.html", assigns %>
  </body>
</html>